<html style="height: 842px; width: 595px; margin-top: 5px; margin-bottom: 5px;">

<body style="height: 842px; width: 595px">
  <div class="container">
    <p style='color: black'>
      <b>
        <center><span style='font-size:16.0pt;font-family:Arial;'>DECODER LEASE AGREEMENT</span></center>
      </b>
    </p>
    <p>
      <span style='font-size:12.0pt;font-family:Arial;'>
        <b>THIS LEASE AGREEMENT</b> is made the date on section 11 of this agreement, <b>BETWEEN MOREPLEX TV Ltd</b>, a
        limited liability company duly incorporated under the laws of the Federal Republic of Nigeria, with registered
        office
        address at <b>NO 15B KUDIRAT ABIOLA WAY, IKEJA, LAGOS NIGERIA</b> (hereinafter called ‘<b>COMPANY</b>’ and shall
        for
        the sake
        of this agreement be referred to as ‘The Company’ which expression shall where the context permits include its
        successors-in-title, privies and assigns) of the first part; AND <br>
      </span><span><b>$LeaseDetails.firstName$ $LeaseDetails.lastName$</b></span>(your full name) with address
      <b>$LeaseDetails.city$ $LeaseDetails.state$ $LeaseDetails.country$</b>
      (hereinafter referred to as “<b>The Customer</b>” which expression shall where the context permits include its
      successors-in-title, privies and assigns) of the other part.
      </span>
    </p>
    <p><b>WHEREAS</b></p>
    <ol>
      <li style='font-size:12.0pt;font-family:Arial;'>
        The Company is the owner and operator of a Direct –To – Home
        Satellite platform known as MOREPLEX TV and is
        desirous of maintaining and smoothly operating same and to give out its Decoders to interested customers for
        lease The Customer has presented to the company his willingness in taking the company’s products for lease and
        capacity to pay the agreed total sum in the manner as in Section 11 of this agreement.
      </li>
      <li style='font-size:12.0pt;font-family:Arial;'>
        Parties have agreed and as such willfully, without duress entered into this agreement.
      </li>
      <li style='font-size:12.0pt;font-family:Arial;'>
        The company reserves the right to make adjustment on this agreement from time to time to the benefit of both
        parties.
      </li>
    </ol>
    <p>
      <b><span style='font-size:12.0pt;font-family:Arial;'>NOW THIS AGREEMENT WITNESSES AS FOLLOWS.</span></b>
    <ol>
      <li style='font-size:12.0pt;font-family:Arial;'>
        <b>
          QUALIFICATION
        </b>
        <p>
          The Customer haven been qualified through an online verification process with the payment of non-refundable
          fee
          of N1,000.00 (One thousand Naira ) ONLY as Processing / logistic fee. The company will issue a decoder to
          customer with terms of payment as stated in section 11 below. All payments shall be made to the designated
          account numbers as provided by the company.
        </p>
        <p>
          The customer agrees to be responsible for payments until paid in full and will forfeit any discount given
          should Customer default.
        </p>
        <p>
          The Customer shall indemnify and hold harmless the company from any and all fines, damages, losses, costs and
          expenses(including reasonable attorneys’ fees) incurred by the Company as a breach of this agreement by the
          Customer
        </p>
      </li>

      <li style='font-size:12.0pt;font-family:Arial;'>
        <b>
          THE COMPANY COVENANTS AS FOLLOWS..
        </b>
      </li>
      <div style='font-size:12.0pt;font-family:Arial;'>
        <p>
         i. The company shall make available to the customer lease agreement and other necessary forms (if any) at the
          company’s head office, or the dealer offices, or online .
        </p>
        <p>
          ii. The Company shall try to make the process swift and ensure that customer takes delivery of their products in
          their different locations especially for the online customers.
        </p>
        <p>
          iii. The company shall be available at all times to offer technical advice and consultation on issues relating to
          the content and subject matter of this agreement.
        </p>
        <p>
          iv. The customer agrees and accepts that online acknowledgement, or scanned document/signature, or electronic
          signature for this agreement, which is adopted to make the process swift, is legally binding on customer.
        </p>
      </div>
    </ol>
    </p>
  </div>
</body>

</html>