<html>

<body>
    <h2>
        DECODER LEASE AGREEMENT
    </h2>
    <p>
        <b>THIS LEASE AGREEMENT</b> is made the date on section 11 of this agreement, <b>BETWEEN MOREPLEX TV Ltd</b>, a
        limited liability company duly incorporated under the laws of the Federal Republic of Nigeria, with registered
        office
        address at <b>NO 15B KUDIRAT ABIOLA WAY, IKEJA, LAGOS NIGERIA</b> (hereinafter called ‘<b>COMPANY</b>’ and shall
        for
        the sake
        of this agreement be referred to as ‘The Company’ which expression shall where the context permits include its
        successors-in-title, privies and assigns) of the first part; AND <br>
        </span><span><b>$LeaseDetails.salutation$ $LeaseDetails.firstName$ $LeaseDetails.lastName$</b></span>(your full name) with address
        <b>$LeaseDetails.city$ $LeaseDetails.state$ $LeaseDetails.country$</b>
        (hereinafter referred to as “<b>The Customer</b>” which expression shall where the context permits include its
        successors-in-title, privies and assigns) of the other part.
    </p>
    <b>WHEREAS</b>
    <p>
        <p>
           1. The Company is the owner and operator of a Direct –To – Home
            Satellite platform known as MOREPLEX TV and is
            desirous of maintaining and smoothly operating same and to give out its Decoders to interested customers for
            lease The Customer has presented to the company his willingness in taking the company’s products for lease
            and
            capacity to pay the agreed total sum in the manner as in Section 11 of this agreement.
        </p>
        <p>
           2. Parties have agreed and as such willfully, without duress entered into this agreement.
        </p>
        <p>
           3. The company reserves the right to make adjustment on this agreement from time to time to the benefit of both
            parties.
        </p>
    </p>
    <h3>
        NOW THIS AGREEMENT WITNESSES AS FOLLOWS.
    </h3>
    <ol>
        <li>
            <p><b>QUALIFICATION</b></p>
            <p>
                The Customer haven been qualified through an online verification process with the payment of
                non-refundable
                fee
                of N1,000.00 (One thousand Naira ) ONLY as Processing / logistic fee. The company will issue a decoder
                to
                customer with terms of payment as stated in section 11 below. All payments shall be made to the
                designated
                account numbers as provided by the company.
            </p>
            <p>
                The customer agrees to be responsible for payments until paid in full and will forfeit any discount
                given
                should Customer default.
            </p>
            <p>
                The Customer shall indemnify and hold harmless the company from any and all fines, damages, losses,
                costs and
                expenses(including reasonable attorneys’ fees) incurred by the Company as a breach of this agreement by
                the
                Customer.
            </p>
        </li><br>
        <li><b>THE COMPANY COVENANTS AS FOLLOWS..</b></li>
        <p>
            i. The company shall make available to the customer lease agreement and other necessary forms (if any) at
            the
            company’s head office, or the dealer offices, or online .
        </p>
        <p>
            ii. The Company shall try to make the process swift and ensure that customer takes delivery of their
            products in
            their different locations especially for the online customers.
        </p>
        <p>
            iii. The company shall be available at all times to offer technical advice and consultation on issues
            relating to
            the content and subject matter of this agreement.
        </p>
        <p>
            iv. The customer agrees and accepts that online acknowledgement, or scanned document/signature, or
            electronic
            signature for this agreement, which is adopted to make the process swift, is legally binding on customer.
        </p>
        <br>
        <b>CUSTOMER COVENANTS AS FOLLOW:</b>
        <p>
            i. The Customer shall read the Lease agreement and any other form /forms thoroughly and provide the CORRECT
            details needed therein.
        </p>
        <p>
            ii. The Customer shall provide His/her bank details, including the BVN and the NIN numbers.
        </p>
        <p>
            iii. The Customer shall provide Valid means of identification
        </p>
        <p>
            iv. The Customer shall make available any proof of capacity for example, a copy of the office I.D cards for
            the working class customers , a copy of Business registration certificate for the business class customers,
            a reliable guarantor and verifiable addresses .
        </p>
        <p>
            v. The Customer shall provide functional phone lines , email addresses and verifiable address and agrees to
            readily update any that changes.
        </p>
        <p>
            vi. The Customer shall give the Company unrestrained access to his/her accounts ONLY for the purpose of
            RECOVERY of the agreed sum for the stipulated number of months agreed by parties which includes but not
            limited to writing /signing a debit note or order to his/her bank / banks.
        </p>
        <p>
            vii. The Customer shall report faulty set top boxes within 2 days of discovery of such fault to the company
            or to the nearest Company’s Dealer, whereas the company shall not be responsible for any willful, careless,
            negligent act or omission occasioning the fault or damage to the set top boxes while in the custody of the
            Customer.
        </p>
        <p>
            viii. Set up boxes already worked on or whose warranties have been broken or removed shall not be received
            or accepted by the company and as such shall not be replaced.
        </p><br>
        <li>
            <p><b>DELIVERY</b></p>
            <p>
                Unless the parties agree otherwise, all products ordered by the Customer shall be sent to the Customer
                within a day before the expected date of delivery depending on the customers location but not later than
                5 working days , except for unforeseen logistic related issues which goes beyond the Company’s control
                of which the Customer will be duly notified.
            </p>
            <p>
                Where the Customer designates an agent, a common carrier or representative (recipient) for delivery of
                ordered products and such products are passed to such recipient, the risk of loss and damages to the
                product shall pass to the Customer upon delivery of such product to the recipient designated by him/her.
            </p>
            <p>
                All claims for non-conforming deliveries must be made in writing to the company or to the nearest Dealer
                within ten (10) days of the passing of the risk of loss and damages, as described above. Any claim not
                made within such period shall be deemed waived and released. The customer shall be responsible for any
                shipping charges to deliver the decoder to the customer.

            </p>
        </li><br>
        <li><b>LIMITED WARRANTY</b>
            <p>
                The Customer acknowledges that all components of the products are being manufactured for the Company by
                subcontractors or other entities other than the Company. Company extends to the Customer the warranties
                as to such components provided by such other entities to the Company for the length of time that such
                warranty remains valid for the company. There shall not be implied warranties
            </p>
        </li><br>
        <li><b>LIMITATION ON LIABILITIES</b>
            <p>
                The Company’s liability arising out of the manufacture, sale or supplying of the products or their use
                or disposition, whether based upon warranty, contract, tort or otherwise, shall not exceed the actual
                purchase price paid by the Customer for the product.
            </p>
            <p>
                In no event shall the Company be liable to the Customer or any other person or entity for special,
                incidental or consequential damages (including but not limited to loss of data or use damages) arising
                out of the manufacture, sale or supply of the products, even if the Company has been advised of the
                possibility of such damages or losses.

            </p>
        </li><br>
        <li><b>FORCE MAJEURE</b>
            <p>
                Neither the Company nor the Customer shall be liable in damages, or shall be subject to termination of
                this agreement by the other party, for any delay or default in performing any obligation hereunder if
                that delay or default is due to any cause beyond the reasonable control and without fault of negligence
                of that party.
            </p>
        </li><br>
        <li><b>INDEMNIFICATION</b>
            <p>
                The Customer hereby agrees to indemnify, defend and hold harmless the company, its affiliates and all
                officers, directors, employees and agents thereof (hereinafter referred to as ‘indemnities’) from all
                liabilities, claims, damages, losses, cost, expenses, demands, suits and actions(including without
                limitation to attorneys’ fees and settlement costs) (collectively, ‘Damages’) arising out of or related
                to
                damage or injury to property or persons, or to any representations of the Customer not authorized
                hereunder.
            </p>
        </li><br>
        <li><b>TERM</b>
            <p>
                The term of this agreement shall commence from the execution date or a date as may be agreed by the
                parties and subject to termination on a later date by either party pursuant to the provisions herein.
            </p>
        </li><br>
        <li><b>TERMINATION</b>
            <p>
                This agreement automatically terminates once the Customer finishes his/her payment of the agreed sum of
                which the company acknowledges same.
            </p>
        </li><br>
        <li><b>GOVERNING LAW AND JURISDICTION</b>
            <p>
                This agreement and any dispute or claim about it or its subject matter is governed by and construed in
                accordance with the laws of the Federal Republic of Nigeria.
            </p>
        </li><br>
        <li><b>INFORMATION & PAYMENT TERMS</b>
            <ol class="r" style="line-height: 1.5;">
                <li>Customer Name: <span><b>$LeaseDetails.salutation$ $LeaseDetails.firstName$ $LeaseDetails.lastName$</b></span></li>
                <li>Customer address:<span><b>$LeaseDetails.city$ $LeaseDetails.state$ $LeaseDetails.country$</b></span></li>
                <li>Customer Phone Number:<span><b>$LeaseDetails.mobileNumber$</b></span></li>
                <li>NIN:<span><b>$LeaseDetails.NIN$</b></span></li>
                <li>BVN:<span><b>$LeaseDetails.BVN$</b></span></li>
                <li>Bank Name:<span></span></li>
                <li>Bank Account Number:<span></span></li>
                <li>Effective Date(Today’s date):<span></span></li>
                <li>Total Amount: <span>&#8358;</span>16,000.00</li>
                <li>Discounted Price: <span>&#8358;</span>12,000.00</li>
                <li>Monthly Lease Payment: <span>&#8358;</span>1,000.00</li>
                <li>Late Payment charges: <span>&#8358;</span>100 per month</li>
                <li>Instalment Payment Due: On the monthly anniversary of the activation date.</li>
                <li>Default: After 30 days of nonpayment.</li>
            </ol>
            <p>
                Customer will own decoder after payment of N12,000.00. This excludes the non-refundable N1,000
                processing fee and any penalty for late payment. 
            </p>
            <p>
                In a case where customer defaults, Customer hereby has authorized Moreplex TV Ltd to collect from the
                above stated bank or any other bank in the world where customer has funds to settle all outstanding
                amount.
            </p>
        </li>
        <p>
            <b> IN WITNESS WHEREOF</b> the parties have executed and affixed their common seals to this agreement the day and year first above written.
        </p><br><br>
        <p>
            <b>SIGNED, SEALED AND DELIVERED BY THE WITHIN NAMED COMPANY</b>
        </p>
        <p>
           <b>Moreplex Director’s Name:</b> 
        </p><br>
        <p>
            <b>Moreplex Director’s Signature:</b>
        </p>
        <p>
            <b>Date:</b>
        </p><br><br>
        <p>
            <b>SIGNED, SEALED AND DELIVERED BY THE WITHIN NAMED CUSTOMER </b>
        </p>
        <p>
            <b>Customer Name:</b>
        </p><br>
        <p>
            <b>Customer Signature:</b>
        </p>
        <p>
            <b>Date:</b>
        </p>
    </ol>
</body>
<style>
    p,
    b,
    ol {
        font-size: 12pt;
        font-family: 'Times New Roman', Times, serif;
    }

    h2 {
        font-size: 16pt;
        font-family: 'Times New Roman', Times, serif;
        text-align: center;
    }

    h3 {
        font-size: 14pt;
        font-family: 'Times New Roman', Times, serif;
    }

    ol.r {
        list-style-type: none;
    }
</style>

</html>